services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "3000:8080" # Avoid default 8080 on host
      - "50000:50000"
    networks:
      - cicd-network
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_logs:/var/log/jenkins
      - jenkins_config:/var/jenkins_config
      - ./gitleaks-output:/path/gitleaks-output # Mount gitleaks-output directory
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker CLI access
volumes:
  jenkins_data:
  jenkins_logs:
  jenkins_config:
networks:
  cicd-network:
    driver: bridge
