services:
  postgres:
    image: postgres:15
    container_name: sonarqube_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpass
      POSTGRES_DB: sonarqube
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
      - postgres_config:/etc/postgresql
    networks:
      - cicd-network
    ports:
      - "3002:5432" # Avoid default 5432 if needed

  sonarqube:
    image: sonarqube:9.9-community
    container_name: sonarqube
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonarpass
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_conf:/opt/sonarqube/conf
    networks:
      - cicd-network
    ports:
      - "9000:9000"
volumes:
  postgres_data:
  postgres_logs:
  postgres_config:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_conf:
networks:
  cicd-network:
    driver: bridge
